# Generated by Django 4.1.4 on 2022-12-08 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitnesskit_task', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sources',
            name='date',
            field=models.DateTimeField(verbose_name='date published'),
        ),
    ]
