# Generated by Django 4.1.4 on 2022-12-10 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitnesskit_task', '0002_alter_sources_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sources',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
