# Generated by Django 4.1.4 on 2022-12-16 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitnesskit_task', '0006_alter_user_image_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sources',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
