# Generated by Django 4.1.4 on 2022-12-20 08:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fitnesskit_task', '0007_alter_sources_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='BasicAuth',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('login', models.CharField(max_length=30)),
                ('password', models.CharField(max_length=30)),
                ('basicauth', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='basicauth', to='fitnesskit_task.sources')),
            ],
        ),
    ]
