# Generated by Django 4.1.4 on 2022-12-20 12:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fitnesskit_task', '0008_basicauth'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='basicauth',
            name='basicauth',
        ),
        migrations.AddField(
            model_name='basicauth',
            name='basic_auth',
            field=models.OneToOneField(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='basic_auth', to='fitnesskit_task.sources'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='basicauth',
            name='login',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='basicauth',
            name='password',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='user',
            name='image_url',
            field=models.CharField(blank=True, default='', max_length=128),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_name',
            field=models.CharField(blank=True, default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='user',
            name='name',
            field=models.CharField(blank=True, default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(blank=True, default='', max_length=12),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_id',
            field=models.CharField(blank=True, default='', max_length=128),
        ),
        migrations.CreateModel(
            name='RequestBody',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_id', models.CharField(default='', max_length=128)),
                ('club_id', models.CharField(default='', max_length=128)),
                ('method', models.CharField(default='', max_length=128)),
                ('request_body', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='request_body', to='fitnesskit_task.sources')),
            ],
        ),
        migrations.CreateModel(
            name='ParametersRequestBody',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_id', models.CharField(default='', max_length=30)),
                ('parameters', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='Parameters', to='fitnesskit_task.requestbody')),
            ],
        ),
    ]
