# Generated by Django 4.1.4 on 2022-12-20 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitnesskit_task', '0009_remove_basicauth_basicauth_basicauth_basic_auth_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='parametersrequestbody',
            old_name='parameters',
            new_name='Parameters',
        ),
        migrations.RenameField(
            model_name='requestbody',
            old_name='club_id',
            new_name='ClubId',
        ),
        migrations.RenameField(
            model_name='requestbody',
            old_name='method',
            new_name='Method',
        ),
        migrations.RenameField(
            model_name='requestbody',
            old_name='request_id',
            new_name='Request_id',
        ),
        migrations.RemoveField(
            model_name='parametersrequestbody',
            name='service_id',
        ),
        migrations.AddField(
            model_name='parametersrequestbody',
            name='ServiceId',
            field=models.CharField(blank=True, default='', max_length=30),
        ),
    ]
