# Generated by Django 4.1.4 on 2022-12-20 15:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fitnesskit_task', '0010_rename_parameters_parametersrequestbody_parameters_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
